require "rake"
require "rdoc/task"
require "rake/testtask"

RDoc::Task.new do |rt|
  rt.rdoc_dir = "doc"
  rt.rdoc_files.include("**/*.rb", "**/*.rdoc", "COPYING")
  rt.rdoc_files.exclude("server/lib/open_ruby_rmk/karfunkel/server_management/requests/*.rb")
  rt.generator = "hanna" #Ignored if not there
  rt.title = "OpenRubyRMK RDocs"
  rt.main = "README.rdoc"
end

Rake::TestTask.new do |t|
  t.test_files = FileList["test/test_*.rb"]
end
